### ISSUE TITLE
Grafana shows no data

### ISSUE THREAD

**Issue by nullric** [rafaelzimmermann/cryptowatcher#2]
Hi, 

Noob question, where do I put the API key?

Thanks for the cool project :D

Edit: The dashboard loaded but with no data

**Comment by rafaelzimmermann** [comment]
Hi, thanks for the interest in the project and for given it a try, I really appreciate it.

You don't need to add a Binance Key, because it uses the public API. You can add a Coin Market Cap apiKey to `cryptowatcher/config.json` like this:

```
{
  "wallet": {
    "ADA": 1000.0,
    "SOL": 100,
    "ETH": 5,
    "BTC": 1
  },
  "tickers": [
    "ADA",
    "BTC",
    "SOL",
    "BNB",
    "DOGE",
    "MBOX",
    "BETH"
  ],
  "currencies": ["EUR", "USDT"],
  "coinMarketCap": {
    "apiKey": "YOUR_KEY_HERE"
  }
}
```

This is used to get prices for coins not supported by Binance, like ELON or CRO.

It get prices every minute, so it can take one or two minutes to show some date on grafana.

Currently the wallet balance is added manually in the config.json, but I am working on a PR to allow importing from csv file exported from Binance, Exodus, crypto.com, and daedalus.

**Comment by nullric** [comment]
Thanks for that. Then I am doing something else wrong since its not loading at all :S

I am also unable to load http://prometheus:9090/ so Im guessing its related to that

Edit: Opened the port (duh) but still not loading. Even simple stuff is hard, should have started learning a long time ago

![image](https://user-images.githubusercontent.com/95101149/143679454-0cfc4e2b-e291-438f-b352-3eb161348518.png)

**Comment by rafaelzimmermann** [comment]
I was able to reproduce the issue.

For some reason when Grafana starts and Prometheus is empty, Grafana is not able to fetch data from Prometheus. If you go to datasource configuration on grafana and save the Prometheus configuration, it will start showing the data. Like this:


https://user-images.githubusercontent.com/2369982/143731793-64e38a53-e75f-4eb2-b2d4-39c8090c6ec8.mov



You can also try the latest version, I fixed the problem by making Grafana to depend on Prometheus and making CryptoWatcher produce data at start up.

https://github.com/rafaelzimmermann/cryptowatcher/commit/3531d1f5a9e1f4649ae3d8ade6507078d1bc0c1a

Thanks you very much for reporting the issue!! Please let me know if the fix works for you.

**Comment by nullric** [comment]
I am still having the issue, its showing no data. I deleted everything and started from zero. I am sure its something obvious that I am missing

**Comment by rafaelzimmermann** [comment]
Can you share your config.json? You can omit or fake the wallet balance to not disclose your balance.
Can you please also share which operational system you are using, and the version of your docker and docker compose?

**Comment by nullric** [comment]
{
  "wallet": {
    "ADA": 0,
    "SOL": 150,
    "ETH": 18,
    "BTC": 2.63
  },
  "tickers": [
    "ADA",
    "BTC",
    "SOL",
    "BNB",
    "DOGE",
    "MBOX",
    "BETH"
  ],
  "currencies": ["EUR", "USDT"]
}

Windows 10
Docker Version: 20.10.10
Docker Compose version v2.1.1

**Comment by rafaelzimmermann** [comment]
I see, I didn't try it on Windows. I tested on OSX and Ubuntu.
I am going to build a virtual machine and try to find out what is happening.

Thanks again! I will keep you posted

**Comment by rafaelzimmermann** [comment]
@ChocoC0kes Can you please check if there is any error in the logs?
You will be able to see the logs by running the docker-compose without the `-d` option

```
docker-compose up
```

**Comment by nullric** [comment]
[+] Running 3/0
 - Container prometheus   Running                                                                                  0.0s
 - Container pushgateway  Running                                                                                  0.0s
 - Container grafana      Running                                                                                  0.0s
Attaching to cryptowatcher, grafana, prometheus, pushgateway
grafana        | t=2021-11-30T13:33:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/api/v1/query_exemplars status=404 remote_addr=172.18.0.1 time_ms=1 size=19 referer="http://127.0.0.1:3000/d/WJea-ZI7k/crypto-price?orgId=1&refresh=30s"
grafana        | t=2021-11-30T13:33:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/api/v1/query_exemplars status=404 remote_addr=172.18.0.1 time_ms=0 size=19 referer="http://127.0.0.1:3000/d/WJea-ZI7k/crypto-price?orgId=1&refresh=30s"
grafana        | t=2021-11-30T13:33:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/api/v1/query_exemplars status=404 remote_addr=172.18.0.1 time_ms=0 size=19 referer="http://127.0.0.1:3000/d/WJea-ZI7k/crypto-price?orgId=1&refresh=30s"
grafana        | t=2021-11-30T13:33:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/api/v1/query_exemplars status=404 remote_addr=172.18.0.1 time_ms=0 size=19 referer="http://127.0.0.1:3000/d/WJea-ZI7k/crypto-price?orgId=1&refresh=30s"


I reinstalled everything and now I get this error as well in docker : /bin/sh: 1: /app/cryptowatcher.py: not found

**Comment by rafaelzimmermann** [comment]
Interesting

can you please try:
```
docker-compose up --force-recreate --build
```

this will force the cryptowatcher to be built again

**Comment by nullric** [comment]
I am getting this error now

/bin/sh: 1: /app/cryptowatcher.py: not found

**Comment by rafaelzimmermann** [comment]
There was a major change in the project, can you please try the latest version?

**Comment by nullric** [comment]
Still no data on Grafana and I get this in Docker:

![image](https://user-images.githubusercontent.com/95101149/147234232-2bc40b96-a555-4da7-a989-8df02fe874bc.png)

: invalid optionsh: line 3: set: -

set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

/app/entrypoint.sh: line 4: $'\r': command not found

/app/entrypoint.sh: line 6: $'\r': command not found

/app/entrypoint.sh: line 14: syntax error: unexpected end of file
